import { SellerProfile } from '@/domains/sellerInfo/types';

export const sellersData: SellerProfile[] = [
    {
        id: '1',
        name: '캣독잇츠',
        profileImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCe4k2k_tSTSzdjMBObPUqsdKg9TiYdEs_G7zKm_W8CI4cuwgxrBfAOUFzKNyxJ2S7i3Is682Q10tV9syiLO3nNYVLyYhP3aRonp_8wSbubS0PSpspeMtvaPL-Uy-GY-DuTOBFtxFpELOMGDUd99U_PIzD8nxTz_mbWbqcaxuwbJF5TpWCSorOVuUQGtxtQdSovC7tSJx8weoxfihS5Nh4lAZbIDOmJnoSnMUtdTN6O9gML9iSv1uhRh-_j2hp1_CQbhPwZ_PIwmUJs',
        rating: 4.8,
        reviewCount: 1234,
        salesCount: 5678,
        establishedYear: 2020,
        tags: ['#수제간식', '#무첨가', '#강아지전용'],
        operatingHours: '09:00 - 18:00 (주말 및 공휴일 휴무)',
        shippingInfo: '평균 3-5일 소요 (CJ대한통운)',
        location: '대한민국 서울',
        isVerified: true,
        isSafetyChecked: true,
        description: '건강한 수제 간식으로 반려동물의 행복을 만들어갑니다.'
    },
    {
        id: '2',
        name: '건강한발자국',
        profileImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3yXOi3RSmIVZCeAst69PCREbx-tkxhiaJzaotI9TtR1ueswlHc4sUZ6mj7UPUncBLtgHiHLLQh2Ew3bcCc5poVwGEVprFuYkh0FFN3zGcpTNu8ED7o9HVlpvTKMqnY0724BKxgCcq4a21b_vO1PxAsgUoNQ1A0nBhAiYwpywi0oINY5EHjM2BnwFDZkYZMTkkTEKavvBjk6EpGYDw0etrHsbzyLFQ15N7BGlwh93wRO5O7VKnYQongqHMdrAiCzM6GSTQDrToK13j',
        rating: 4.9,
        reviewCount: 892,
        salesCount: 3456,
        establishedYear: 2019,
        tags: ['#유기농', '#건강간식', '#전견종'],
        operatingHours: '10:00 - 19:00 (일요일 휴무)',
        shippingInfo: '평균 2-4일 소요 (로젠택배)',
        location: '대한민국 부산',
        isVerified: true,
        isSafetyChecked: true,
        description: '유기농 강아지 간식 전문'
    },
    {
        id: '3',
        name: '야옹이네부엌',
        profileImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBV29DkmRCZISm2oAFSO1zS2fz6bVd4EbaFZplu94910Pzw2t_z4VfC_ioo7rIEkGvAnJ0uqVgarUcoxPbcMB_ilcrqyQd2V29XmJSXgO3Yxp23pDSj1b8JmOohRgTFxonRDQeLyc9PbfdjrCJr0X6ChbtdQpeEBbOPygQDFRR9ybZMb_zTvpSrv47QXkElp2vxSi-VAubSRavKIsHZCbs8zxJcpnUc2qRLnQtzaJXSDMFyGTq_vRtz4X_YV2V2UZyp_Wife3zAHDa-',
        rating: 4.7,
        reviewCount: 567,
        salesCount: 2134,
        establishedYear: 2021,
        tags: ['#고양이전용', '#까다로운입맛', '#프리미엄'],
        operatingHours: '09:30 - 18:30 (토일 휴무)',
        shippingInfo: '평균 3-5일 소요 (한진택배)',
        location: '대한민국 대구',
        isVerified: true,
        isSafetyChecked: false,
        description: '까다로운 고양이 입맛 저격'
    },
    {
        id: '4',
        name: '펫푸드마켓',
        profileImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7x1jZHmSOSaPmZN4hCTkgCVOE6QoOUkuxNBhGT9pZO1Lg1hRw9ahPVDGwwDaU0AS611nJMboXnp6huRxYPvizlfwB4aO_uBxCoDhz26zT3ejpzPATvq1c1fLkkwQTvanExwzKbeQBM20uDW1KCO1raAbCfwiWnI2PH81vT2K-yOZGhHK3sHdZjiQUksDBPr_8qXQl1ccuSdjIJYq5PggjcZ4YF4VJvm1UjGrQhjHUrGGTl_6phYWXJxFy51NfvYwmgWRVOSuyDRqh',
        rating: 4.6,
        reviewCount: 1456,
        salesCount: 7890,
        establishedYear: 2018,
        tags: ['#다양한용품', '#합리적가격', '#빠른배송'],
        operatingHours: '08:00 - 20:00 (연중무휴)',
        shippingInfo: '평균 1-3일 소요 (당일배송 가능)',
        location: '대한민국 인천',
        isVerified: true,
        isSafetyChecked: true,
        description: '다양한 반려동물 용품'
    },
    {
        id: '5',
        name: '자연이준선물',
        profileImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWJyIaeJK-oRQQP2VzpxlzDl8i9azg0ufAt2LXmWJesVZgUuQ44Aekf6f2J4hZvNM74NzZXwXWiDJ2jdyI_B6FOhjocMBxMTu6Eyr4cMVvZRuBdS5hQHEPu30fbtwbKRo1uHDYt0LoYmjms-jqoWygT1d0Os9rHkYzfJW38bFTkbeMSgybO0h0cCIyLLyfUE3Ctv__ENFVf7G0NkcxhxJOZ4ol1s2XNoO-_r_l3R0QUx6NNHwejigkU-cVJboheJ4iIuy2pcwTIcAp',
        rating: 4.5,
        reviewCount: 234,
        salesCount: 890,
        establishedYear: 2022,
        tags: ['#자연재료', '#모든반려동물', '#친환경'],
        operatingHours: '10:00 - 18:00 (주말 휴무)',
        shippingInfo: '평균 4-6일 소요 (우체국택배)',
        location: '대한민국 광주',
        isVerified: false,
        isSafetyChecked: true,
        description: '모든 반려동물을 위한 간식'
    },
    {
        id: '6',
        name: '튼튼펫푸드',
        profileImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3yXOi3RSmIVZCeAst69PCREbx-tkxhiaJzaotI9TtR1ueswlHc4sUZ6mj7UPUncBLtgHiHLLQh2Ew3bcCc5poVwGEVprFuYkh0FFN3zGcpTNu8ED7o9HVlpvTKMqnY0724BKxgCcq4a21b_vO1PxAsgUoNQ1A0nBhAiYwpywi0oINY5EHjM2BnwFDZkYZMTkkTEKavvBjk6EpGYDw0etrHsbzyLFQ15N7BGlwh93wRO5O7VKnYQongqHMdrAiCzM6GSTQDrToK13j',
        rating: 4.8,
        reviewCount: 678,
        salesCount: 2345,
        establishedYear: 2020,
        tags: ['#수제영양간식', '#건강한재료', '#맞춤제작'],
        operatingHours: '09:00 - 17:00 (토일 휴무)',
        shippingInfo: '평균 3-4일 소요 (CJ대한통운)',
        location: '대한민국 대전',
        isVerified: true,
        isSafetyChecked: true,
        description: '수제 영양 간식 전문'
    }
];
