import { Workshop } from '@/domains/workshop/types';

export const popularWorkshops: Workshop[] = [
    {
        id: '1',
        name: '사랑가득 엄마손길',
        description: '유기농 재료로 만드는 건강 간식 전문',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=200&fit=crop',
        rating: 4.8,
        reviewCount: 234,
        specialties: ['유기농', '건강간식', '수제'],
        location: '서울 강남구',
        established: '2020',
    },
    {
        id: '2',
        name: '댕댕이 쉐프',
        description: '특별한 날을 위한 맞춤 케이크 & 쿠키',
        image: 'https://images.unsplash.com/photo-1581888227599-779811939961?w=400&h=200&fit=crop',
        rating: 4.6,
        reviewCount: 187,
        specialties: ['케이크', '쿠키', '맞춤제작'],
        location: '서울 홍대',
        established: '2019',
    },
    {
        id: '3',
        name: '냥이네 부엌',
        description: '까다로운 냥님 입맛 저격! 영양만점 간식',
        image: 'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=400&h=200&fit=crop',
        rating: 4.7,
        reviewCount: 156,
        specialties: ['고양이 전문', '영양간식', '프리미엄'],
        location: '부산 해운대구',
        established: '2021',
    },
    {
        id: '4',
        name: '펫츠 헬시 키친',
        description: '건강을 생각하는 반려동물 전용 간식',
        image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&h=200&fit=crop',
        rating: 4.5,
        reviewCount: 98,
        specialties: ['건강식', '다이어트', '시니어'],
        location: '대구 수성구',
        established: '2022',
    },
    {
        id: '5',
        name: '자연애 공방',
        description: '자연 그대로의 맛을 살린 무첨가 간식',
        image: 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=400&h=200&fit=crop',
        rating: 4.4,
        reviewCount: 143,
        specialties: ['무첨가', '자연식', '소량생산'],
        location: '제주도',
        established: '2018',
    },
];